version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: codedeploy-taskdefination
        LoadBalancerInfo:
          ContainerName: app
          ContainerPort: 8080
